# Login to Azure
Connect-AzAccount

# Define and assign Policy Sets (initiatives) to Management Groups
$custodianServicesInitiative = New-AzPolicySetDefinition -Name 'custodian-services' -DisplayName 'Custodian Services' -Description 'Initiative for custodian services' -PolicyDefinition '.\2 - Initiatives\custodian-services-initiative.json' -ManagementGroupName 'custodian-services' -Parameter '{ "AllowedLocations": { "type": "array" } }'
$division1ProjectsInitiative = New-AzPolicySetDefinition -Name 'division-1-projects' -DisplayName 'Division 1 Projects' -Description 'Initiative for division 1 projects' -PolicyDefinition '.\2 - Initiatives\division-1-projects-initiative.json' -ManagementGroupName 'division-1-projects' -Parameter '{ "AllowedLocations": { "type": "array" } }'
$division2ProjectsInitiative = New-AzPolicySetDefinition -Name 'division-2-projects' -DisplayName 'Division 2 Projects' -Description 'Initiative for division 2 projects' -PolicyDefinition '.\2 - Initiatives\division-2-projects-initiative.json' -ManagementGroupName 'division-2-projects' -Parameter '{ "AllowedLocations": { "type": "array" } }'

New-AzPolicyAssignment -Name 'custodian-services' -DisplayName 'Custodian Services' -Description 'Initiative for custodian services' -PolicySetDefinition $custodianServicesInitiative -AllowedLocations '["WestEurope", "NorthEurope"]' -Scope '/providers/Microsoft.Management/managementgroups/custodian-services'
New-AzPolicyAssignment -Name 'division-1-projects' -DisplayName 'Division 1 Projects' -Description 'Initiative for division 1 projects' -PolicySetDefinition $division1ProjectsInitiative -AllowedLocations '["WestEurope", "NorthEurope"]' -Scope '/providers/Microsoft.Management/managementgroups/division-1-projects'
New-AzPolicyAssignment -Name 'division-2-projects' -DisplayName 'Division 2 Projects' -Description 'Initiative for division 2 projects' -PolicySetDefinition $division2ProjectsInitiative -AllowedLocations '["WestEurope", "NorthEurope"]' -Scope '/providers/Microsoft.Management/managementgroups/division-2-projects'