name: manage-azure-policy-48d9ccfd
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - '3 - Core Policy Set/policies/Deny_reserved_names_for_Azure_resources_cbacc846-3441-4372-b437-dcc6fce4a72e/**'
#      - '3 - Core Policy Set/policies/Allow_Role_Definitions_in_IAM_ef4a162f-dbe4-4c26-84e5-103d65e26d97/**'
#      - '3 - Core Policy Set/policies/Audit_NSG_on_NIC_f63293a4-3a70-4c66-9e64-586befd3454c/**'
#      - '3 - Core Policy Set/policies/Enforce_Image_Publishers_f63293a4-3a70-4c66-9e64-586befd34d01/**'
#      - .github/workflows/manage-azure-policy-48d9ccfd.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_48d9ccfd}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          3 - Core Policy Set/policies/Deny_reserved_names_for_Azure_resources_cbacc846-3441-4372-b437-dcc6fce4a72e/**
          3 - Core Policy Set/policies/Allow_Role_Definitions_in_IAM_ef4a162f-dbe4-4c26-84e5-103d65e26d97/**
          3 - Core Policy Set/policies/Audit_NSG_on_NIC_f63293a4-3a70-4c66-9e64-586befd3454c/**
          3 - Core Policy Set/policies/Enforce_Image_Publishers_f63293a4-3a70-4c66-9e64-586befd34d01/**
